// GENERATED by scripts/generate-personas.mjs - do not edit by hand.
// Counts derived from data/compendium.tsv so they cannot drift from the data.
export const PERSONA_COUNT = 213;
export const ARCANA_COUNT = 22;
